# Generated by Django 4.2.2 on 2024-04-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accessory_article_chargingstation_alter_like_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Accessory', 'verbose_name_plural': 'Accessories'},
        ),
    ]
